export const lifeCategories = [
  { key: "fitness", label: "健身" },
  { key: "travel", label: "旅行" },
  { key: "hiking", label: "爬山" },
  { key: "moments", label: "时刻" },
];

export type LifeItem = {
  id: string;
  category: string;
  title: string;
  desc: string;
  date: string; // YYYY-MM-DD
  src: string;
  orientation: "landscape" | "portrait";
  featured: boolean; // 是否在该分类的精选页展示
  bestOfBest?: boolean; // 是否在"精选"标签页展示（优中选优）
  layout?: "normal" | "wide"; // 精选网格布局，仅 featured / bestOfBest 有效
  // 新增可选字段，用于分类差异化展示
  images?: string[]; // travel: 一个 Stack 内的多张照片
  landscapeImage?: string; // hiking: 风景照
  bandImage?: string; // hiking: 运动手环记录截图
};

export type FitnessRecord = {
  date: string; // YYYY-MM-DD
  type: "strength" | "cardio" | "outdoor" | "rest";
  duration: number; // 分钟
  note?: string;
};

export const fitnessRecords: FitnessRecord[] = [
  // 2026-03
  { date: "2026-03-24", type: "strength", duration: 60, note: "胸+三头" },
  { date: "2026-03-25", type: "cardio", duration: 45, note: "跑步机 5km" },
  { date: "2026-03-27", type: "strength", duration: 70, note: "背+二头" },
  { date: "2026-03-29", type: "outdoor", duration: 90, note: "户外骑行" },
  { date: "2026-03-30", type: "strength", duration: 60, note: "腿部训练" },
  { date: "2026-03-31", type: "cardio", duration: 40, note: "椭圆机" },
  // 2026-04
  { date: "2026-04-02", type: "strength", duration: 65, note: "肩+核心" },
  { date: "2026-04-07", type: "cardio", duration: 50, note: "游泳 1km" },
  { date: "2026-04-08", type: "strength", duration: 60, note: "胸+三头" },
  { date: "2026-04-09", type: "strength", duration: 75, note: "背+二头" },
  { date: "2026-04-10", type: "outdoor", duration: 80, note: "公园慢跑" },
  { date: "2026-04-13", type: "strength", duration: 60, note: "腿部训练" },
  { date: "2026-04-14", type: "cardio", duration: 45, note: "跑步机间歇" },
  { date: "2026-04-15", type: "strength", duration: 70, note: "肩+核心" },
];

export const lifeItems: LifeItem[] = [
  // ==================== fitness ====================
  // 精选网格保留少量代表性照片
  {
    id: "f-01",
    category: "fitness",
    title: "冲浪者",
    desc: "等待一个完美的浪，和等待一个灵感一样需要耐心。",
    date: "2024-08-12",
    src: "/images/life/fitness/two-surfers-wait-for-waves-near-a-rocky-coastline-MA0nBwOmuwQ.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
  },
  {
    id: "f-02",
    category: "fitness",
    title: "雪山滑雪",
    desc: "背着装备站在雪坡上，下一步就是与重力共舞。",
    date: "2024-02-20",
    src: "/images/life/fitness/a-skier-with-a-bag-on-a-snowy-slope-bY7uZyolzGk.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
  },

  // ==================== hiking ====================
  {
    id: "h-01",
    category: "hiking",
    title: "山与野花",
    desc: "富士山下的秋日，风一吹，整片芦苇都在发光。",
    date: "2024-10-05",
    src: "/images/life/hiking/a-majestic-mountain-peak-behind-wildflowers-under-a-clear-sky-ho0_jE0q9T0.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
    landscapeImage: "/images/life/hiking/a-majestic-mountain-peak-behind-wildflowers-under-a-clear-sky-ho0_jE0q9T0.jpeg",
    bandImage: "/images/life/fitness/a-skier-with-a-bag-on-a-snowy-slope-bY7uZyolzGk.jpeg",
  },
  {
    id: "h-02",
    category: "hiking",
    title: "云海山峦",
    desc: "站在山脊上，看云雾从谷底缓缓升起。",
    date: "2024-07-14",
    src: "/images/life/hiking/a-mountain-range-with-clouds-in-the-sky-cJgG4wbjkdQ.jpeg",
    orientation: "landscape",
    featured: true,
    layout: "normal",
    landscapeImage: "/images/life/hiking/a-mountain-range-with-clouds-in-the-sky-cJgG4wbjkdQ.jpeg",
    bandImage: "/images/life/fitness/two-surfers-wait-for-waves-near-a-rocky-coastline-MA0nBwOmuwQ.jpeg",
  },
  {
    id: "h-03",
    category: "hiking",
    title: "林间溪流",
    desc: "阳光穿透树林，河水在石间跳跃。",
    date: "2024-06-22",
    src: "/images/life/hiking/a-rocky-river-flows-through-a-sunlit-forest-valley-jXdi_jWuXwA.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "wide",
    landscapeImage: "/images/life/hiking/a-rocky-river-flows-through-a-sunlit-forest-valley-jXdi_jWuXwA.jpeg",
    bandImage: "/images/life/fitness/a-skier-with-a-bag-on-a-snowy-slope-bY7uZyolzGk.jpeg",
  },
  {
    id: "h-04",
    category: "hiking",
    title: "雪夜帐篷",
    desc: "零下十度的星空下，一盏灯撑起一个温暖的小世界。",
    date: "2024-01-08",
    src: "/images/life/hiking/glowing-tent-set-up-in-a-snowy-landscape-at-night-6uhTmirqHlA.jpeg",
    orientation: "landscape",
    featured: true,
    layout: "normal",
    landscapeImage: "/images/life/hiking/glowing-tent-set-up-in-a-snowy-landscape-at-night-6uhTmirqHlA.jpeg",
    bandImage: "/images/life/fitness/two-surfers-wait-for-waves-near-a-rocky-coastline-MA0nBwOmuwQ.jpeg",
  },
  {
    id: "h-05",
    category: "hiking",
    title: "日照金山",
    desc: "日落前的最后一束光，点燃了雪山顶峰。",
    date: "2023-11-03",
    src: "/images/life/hiking/snow-capped-mountain-peak-illuminated-by-golden-sunset-light-7LgwmO6cDrU.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
    landscapeImage: "/images/life/hiking/snow-capped-mountain-peak-illuminated-by-golden-sunset-light-7LgwmO6cDrU.jpeg",
    bandImage: "/images/life/fitness/a-skier-with-a-bag-on-a-snowy-slope-bY7uZyolzGk.jpeg",
  },
  {
    id: "h-06",
    category: "hiking",
    title: "雪山警示",
    desc: "黄黑相间的标志牌，是荒野对人类最温柔的提醒。",
    date: "2023-09-18",
    src: "/images/life/hiking/yellow-warning-sign-in-a-snowy-mountain-landscape-X6pHcOzJVRI.jpeg",
    orientation: "portrait",
    featured: false,
    landscapeImage: "/images/life/hiking/yellow-warning-sign-in-a-snowy-mountain-landscape-X6pHcOzJVRI.jpeg",
    bandImage: "/images/life/fitness/two-surfers-wait-for-waves-near-a-rocky-coastline-MA0nBwOmuwQ.jpeg",
  },

  // ==================== photography ====================
  {
    id: "p-01",
    category: "photography",
    title: "火箭升空",
    desc: "见证一束光撕裂夜空，那是人类最浪漫的倔强。",
    date: "2024-09-20",
    src: "/images/life/photography/rocket-launching-at-night-with-bright-flames-and-smoke--tT9l_dkakk.jpeg",
    orientation: "landscape",
    featured: true,
    layout: "wide",
  },
  {
    id: "p-02",
    category: "photography",
    title: "日落海浪",
    desc: "橙红色的天空倒映在海面上，浪潮一层一层涌来。",
    date: "2024-08-03",
    src: "/images/life/photography/ocean-waves-at-sunset-with-warm-orange-sky-eSLJG0y5S4U.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
  },
  {
    id: "p-03",
    category: "photography",
    title: "海岸礁石",
    desc: "浪花撞击礁石的瞬间，是大海最沉默的呐喊。",
    date: "2024-07-28",
    src: "/images/life/photography/rocky-coastline-with-waves-crashing-against-shore-AImfs6Xh1ZA.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "wide",
  },
  {
    id: "p-04",
    category: "photography",
    title: "落日飞鸟",
    desc: "海鸟掠过黄昏的天际线，像一封没有地址的信。",
    date: "2024-06-15",
    src: "/images/life/photography/a-bird-flies-across-a-hazy-sunset-over-the-ocean-t2vrK9yL2Bg.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
  },
  {
    id: "p-05",
    category: "photography",
    title: "叶上蝴蝶",
    desc: "翅膀上的纹路，是大自然写下的诗。",
    date: "2024-05-02",
    src: "/images/life/photography/a-butterfly-on-a-leaf-Kl3MvqEPJmY.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
  },
  {
    id: "p-06",
    category: "photography",
    title: "蓝色漩涡",
    desc: "抽象的蓝白交织，像思绪在脑海中翻涌。",
    date: "2024-04-10",
    src: "/images/life/photography/abstract-blue-and-white-swirling-patterns-f9PtNFb9_iE.jpeg",
    orientation: "landscape",
    featured: false,
  },
  {
    id: "p-07",
    category: "photography",
    title: "郁金香田",
    desc: "整片黄色的花海，是春天最直白的告白。",
    date: "2024-03-25",
    src: "/images/life/photography/field-of-bright-yellow-tulips-in-bloom-Q_jNh-j8ybo.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "p-08",
    category: "photography",
    title: "键帽心事",
    desc: "四个按键，藏着创作者最常问自己的问题。",
    date: "2024-03-08",
    src: "/images/life/photography/four-keyboard-keys-with-words-and-symbols-48sADbm-Zvg.jpeg",
    orientation: "landscape",
    featured: false,
  },
  {
    id: "p-09",
    category: "photography",
    title: "满月当空",
    desc: "城市灯光再亮，也盖不住这一轮清辉。",
    date: "2024-02-24",
    src: "/images/life/photography/full-moon-glowing-in-the-dark-night-sky-mj_PJw9KZh4.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "p-10",
    category: "photography",
    title: "绿桥繁花",
    desc: "春日的桥与河，连空气都是粉色的。",
    date: "2024-02-14",
    src: "/images/life/photography/green-bridge-over-river-with-blooming-trees-in-foreground-BwQb8kPxl7w.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "p-11",
    category: "photography",
    title: "沙滩碎浪",
    desc: "潮水退去后，沙滩上留下交错的纹理。",
    date: "2024-01-20",
    src: "/images/life/photography/ocean-waves-crashing-on-a-sandy-beach-tu0sNnvcAYQ.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "p-12",
    category: "photography",
    title: "三角梅花",
    desc: "橙红色的花簇映着淡蓝的天空，热烈又安静。",
    date: "2023-12-12",
    src: "/images/life/photography/orange-bougainvillea-flowers-against-a-pale-sky-v8HyIkglUjA.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "p-13",
    category: "photography",
    title: "海岸植被",
    desc: "礁石、海浪与岸边的绿色植物，构成一幅自然的画卷。",
    date: "2023-11-28",
    src: "/images/life/photography/rocky-coastline-with-ocean-waves-and-coastal-plants-urV8KO0pJ9w.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "p-14",
    category: "photography",
    title: "海鸥与夕阳",
    desc: "它们飞向落日，像是去完成某个古老的约定。",
    date: "2023-10-15",
    src: "/images/life/photography/seagulls-fly-over-the-ocean-at-sunset-HcbMxftVAOo.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "p-15",
    category: "photography",
    title: "海平落日",
    desc: "太阳慢慢沉入海平面，世界进入温柔的静默。",
    date: "2023-09-30",
    src: "/images/life/photography/sun-setting-over-a-calm-ocean-horizon-jADSDvEZJpM.jpeg",
    orientation: "landscape",
    featured: false,
  },
  {
    id: "p-16",
    category: "photography",
    title: "黄昏立面",
    desc: "夕阳照亮建筑的一角，城市也有它的黄金时刻。",
    date: "2023-08-22",
    src: "/images/life/photography/sunlight-illuminates-a-building-facade-at-dusk-bjl4lrkxjzs.jpeg",
    orientation: "portrait",
    featured: false,
  },

  // ==================== travel ====================
  {
    id: "t-01",
    category: "travel",
    title: "香格里拉秘境",
    desc: "雪山、佛塔、峡谷与古树，香格里拉的每一帧都像秘境。",
    date: "2025-03-10",
    src: "/images/life/travel/balagezong.jpg",
    orientation: "landscape",
    featured: true,
    layout: "wide",
    images: [
      "/images/life/travel/balagezong.jpg",
      "/images/life/travel/xiangbala-fota.jpg",
      "/images/life/travel/huiyinbi.jpg",
      "/images/life/travel/qiannian-puti.jpg",
    ],
  },
  {
    id: "t-03",
    category: "travel",
    title: "香格里拉站",
    desc: "列车缓缓驶入站台，带着旅人的期待与故事。",
    date: "2025-03-12",
    src: "/images/life/travel/xianggelila-station.jpg",
    orientation: "landscape",
    featured: true,
    layout: "normal",
    images: ["/images/life/travel/xianggelila-station.jpg"],
  },
  {
    id: "t-04",
    category: "travel",
    title: "落日帆船",
    desc: "古老的三桅帆船驶向夕阳，时间仿佛倒流了几个世纪。",
    date: "2024-06-18",
    src: "/images/life/travel/a-tall-ship-sails-on-the-ocean-at-sunset-NJCEGWjzA38.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
    images: ["/images/life/travel/a-tall-ship-sails-on-the-ocean-at-sunset-NJCEGWjzA38.jpeg"],
  },
  {
    id: "t-05",
    category: "travel",
    title: "五彩渔村",
    desc: "地中海的蓝色海水边，彩色房屋像积木一样堆叠。",
    date: "2024-05-25",
    src: "/images/life/travel/colorful-buildings-line-a-rocky-cove-with-clear-blue-water-YelA9YJAPq8.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
    images: ["/images/life/travel/colorful-buildings-line-a-rocky-cove-with-clear-blue-water-YelA9YJAPq8.jpeg"],
  },
  {
    id: "t-08",
    category: "travel",
    title: "雪山列车",
    desc: "瑞士少女峰下的红色火车，像是从童话里开出来的。",
    date: "2024-07-10",
    src: "/images/life/travel/a-red-train-travels-through-a-snowy-mountain-landscape-jllQYsBvFnA.jpeg",
    orientation: "portrait",
    featured: false,
    images: ["/images/life/travel/a-red-train-travels-through-a-snowy-mountain-landscape-jllQYsBvFnA.jpeg"],
  },
  {
    id: "t-09",
    category: "travel",
    title: "摩天轮",
    desc: "游乐园的摩天轮缓缓转动，每一格都装着不同的故事。",
    date: "2024-04-14",
    src: "/images/life/travel/colorful-ferris-wheel-against-a-pale-sky-0j3TlmE8jFA.jpeg",
    orientation: "portrait",
    featured: false,
    images: ["/images/life/travel/colorful-ferris-wheel-against-a-pale-sky-0j3TlmE8jFA.jpeg"],
  },
  {
    id: "t-10",
    category: "travel",
    title: "埃菲尔铁塔",
    desc: "从战神广场望去，紫色的薰衣草与铁塔构成最巴黎的画面。",
    date: "2024-03-30",
    src: "/images/life/travel/eiffel-tower-viewed-from-a-park-with-purple-grass-n8HXOc4O_IM.jpeg",
    orientation: "portrait",
    featured: false,
    images: ["/images/life/travel/eiffel-tower-viewed-from-a-park-with-purple-grass-n8HXOc4O_IM.jpeg"],
  },
  {
    id: "t-11",
    category: "travel",
    title: "小镇街道",
    desc: "历史感的 storefronts 排列在石板路两旁，每一步都是风景。",
    date: "2024-02-18",
    src: "/images/life/travel/historic-storefronts-line-a-charming-small-town-street-iVINr8-ZFmY.jpeg",
    orientation: "landscape",
    featured: false,
    images: ["/images/life/travel/historic-storefronts-line-a-charming-small-town-street-iVINr8-ZFmY.jpeg"],
  },
  {
    id: "t-12",
    category: "travel",
    title: "霍尔木兹海峡",
    desc: "伊朗与阿曼之间的狭窄水域，承载着千年的贸易与文明。",
    date: "2024-01-05",
    src: "/images/life/travel/strait-of-hormuz-between-iran-and-oman-8koWngCqqzM.jpeg",
    orientation: "landscape",
    featured: false,
    images: ["/images/life/travel/strait-of-hormuz-between-iran-and-oman-8koWngCqqzM.jpeg"],
  },
  {
    id: "t-13",
    category: "travel",
    title: "桥上列车",
    desc: "夕阳中的列车穿过桥梁，远处大教堂的尖顶刺破天际。",
    date: "2023-11-20",
    src: "/images/life/travel/train-crossing-a-bridge-with-cathedral-in-background-at-sunset-WaxPv3S-EXM.jpeg",
    orientation: "landscape",
    featured: false,
    images: ["/images/life/travel/train-crossing-a-bridge-with-cathedral-in-background-at-sunset-WaxPv3S-EXM.jpeg"],
  },

  // ==================== moments ====================
  {
    id: "m-01",
    category: "moments",
    title: "火箭升空",
    desc: "见证一束光撕裂夜空。",
    date: "2024-09-20",
    src: "/images/life/photography/rocket-launching-at-night-with-bright-flames-and-smoke--tT9l_dkakk.jpeg",
    orientation: "landscape",
    featured: true,
    layout: "wide",
  },
  {
    id: "m-02",
    category: "moments",
    title: "日落海浪",
    desc: "橙红色的天空倒映在海面上。",
    date: "2024-08-03",
    src: "/images/life/photography/ocean-waves-at-sunset-with-warm-orange-sky-eSLJG0y5S4U.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
  },
  {
    id: "m-03",
    category: "moments",
    title: "叶上蝴蝶",
    desc: "翅膀上的纹路，是大自然写下的诗。",
    date: "2024-05-02",
    src: "/images/life/photography/a-butterfly-on-a-leaf-Kl3MvqEPJmY.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
  },
  {
    id: "m-04",
    category: "moments",
    title: "绿桥繁花",
    desc: "春日的桥与河，连空气都是粉色的。",
    date: "2024-02-14",
    src: "/images/life/photography/green-bridge-over-river-with-blooming-trees-in-foreground-BwQb8kPxl7w.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
  },
  {
    id: "m-05",
    category: "moments",
    title: "五彩渔村",
    desc: "地中海的蓝色海水边，彩色房屋像积木一样堆叠。",
    date: "2024-05-25",
    src: "/images/life/travel/colorful-buildings-line-a-rocky-cove-with-clear-blue-water-YelA9YJAPq8.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-06",
    category: "moments",
    title: "日照金山",
    desc: "日落前的最后一束光，点燃了雪山顶峰。",
    date: "2023-11-03",
    src: "/images/life/hiking/snow-capped-mountain-peak-illuminated-by-golden-sunset-light-7LgwmO6cDrU.jpeg",
    orientation: "portrait",
    featured: false,
  },

  // ==================== featured (homepage bestOfBest) ====================
  {
    id: "feat-01",
    category: "featured",
    title: "泰山",
    desc: "",
    date: "2023-11-02",
    src: "/images/life/featured/taishan.jpg",
    orientation: "portrait",
    featured: true,
    bestOfBest: true,
    layout: "normal",
  },
  {
    id: "feat-02",
    category: "featured",
    title: "黄山",
    desc: "",
    date: "2024-05-02",
    src: "/images/life/featured/huangshan.jpg",
    orientation: "landscape",
    featured: true,
    bestOfBest: true,
    layout: "wide",
  },
  {
    id: "feat-03",
    category: "featured",
    title: "云杉坪",
    desc: "",
    date: "2024-12-31",
    src: "/images/life/featured/yunshanping.jpg",
    orientation: "landscape",
    featured: true,
    bestOfBest: true,
    layout: "wide",
  },
  {
    id: "feat-zhuanjing",
    category: "featured",
    title: "转经筒",
    desc: "",
    date: "2023-11-04",
    src: "/images/life/featured/zhuanjingtong.jpg",
    orientation: "portrait",
    featured: true,
    bestOfBest: true,
    layout: "normal",
  },
  {
    id: "feat-06",
    category: "featured",
    title: "东方明珠",
    desc: "",
    date: "2024-10-13",
    src: "/images/life/featured/dongfangmingzhu.jpg",
    orientation: "landscape",
    featured: true,
    bestOfBest: true,
    layout: "normal",
  },
  {
    id: "feat-07",
    category: "featured",
    title: "松赞干布寺",
    desc: "",
    date: "2025-01-04",
    src: "/images/life/featured/songzanganbusi.jpg",
    orientation: "landscape",
    featured: true,
    bestOfBest: true,
    layout: "normal",
  },
  {
    id: "feat-08",
    category: "featured",
    title: "香巴拉佛塔",
    desc: "",
    date: "2025-01-03",
    src: "/images/life/featured/xiangbalafota.jpg",
    orientation: "landscape",
    featured: true,
    bestOfBest: true,
    layout: "normal",
  },
];

export function getFeaturedItems(category: string) {
  if (category === "all") {
    return lifeItems.filter((item) => item.bestOfBest);
  }
  return lifeItems.filter((item) => item.category === category && item.featured);
}

export function getTimelineItems(category: string) {
  if (category === "all") {
    return lifeItems
      .filter((item) => item.bestOfBest)
      .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  }
  return lifeItems
    .filter((item) => item.category === category)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export function getCategoryLabel(key: string) {
  return lifeCategories.find((c) => c.key === key)?.label ?? key;
}

export function getFitnessRecords() {
  return [...fitnessRecords].sort(
    (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
  );
}
