export const lifeCategories = [
  { key: "arsenal", label: "阿森纳" },
  { key: "fitness", label: "健身" },
  { key: "travel", label: "旅行" },
  { key: "moments", label: "时刻" },
];

export type LifeItem = {
  id: string;
  category: string;
  title: string;
  desc: string;
  date: string; // YYYY-MM-DD
  src: string;
  orientation: "landscape" | "portrait";
  featured: boolean; // 是否在该分类的精选页展示
  bestOfBest?: boolean; // 是否在"精选"标签页展示（优中选优）
  layout?: "normal" | "wide"; // 精选网格布局，仅 featured / bestOfBest 有效
  // 新增可选字段，用于分类差异化展示
  images?: string[]; // travel: 一个 Stack 内的多张照片
  landscapeImage?: string; // hiking: 风景照
  bandImage?: string; // hiking: 运动手环记录截图
};

export type FitnessRecord = {
  date: string; // YYYY-MM-DD
  type: "strength" | "cardio" | "outdoor" | "rest";
};

export const fitnessRecords: FitnessRecord[] = [
  // 2026-03
  { date: "2026-03-24", type: "strength" },
  { date: "2026-03-25", type: "cardio" },
  { date: "2026-03-27", type: "strength" },
  { date: "2026-03-29", type: "outdoor" },
  { date: "2026-03-30", type: "strength" },
  { date: "2026-03-31", type: "cardio" },
  // 2026-04
  { date: "2026-04-02", type: "strength" },
  { date: "2026-04-07", type: "cardio" },
  { date: "2026-04-08", type: "strength" },
  { date: "2026-04-09", type: "strength" },
  { date: "2026-04-10", type: "outdoor" },
  { date: "2026-04-13", type: "strength" },
  { date: "2026-04-14", type: "cardio" },
  { date: "2026-04-15", type: "strength" },
  { date: "2026-04-16", type: "cardio" },
  { date: "2026-04-17", type: "cardio" },
  { date: "2026-04-18", type: "strength" },
  { date: "2026-04-19", type: "cardio" },
];

export const lifeItems: LifeItem[] = [
  // ==================== fitness ====================
  // 精选网格保留少量代表性照片
  {
    id: "f-01",
    category: "fitness",
    title: "冲浪者",
    desc: "等待一个完美的浪，和等待一个灵感一样需要耐心。",
    date: "2024-08-12",
    src: "/images/life/fitness/two-surfers-wait-for-waves-near-a-rocky-coastline-MA0nBwOmuwQ.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
  },
  {
    id: "f-02",
    category: "fitness",
    title: "雪山滑雪",
    desc: "背着装备站在雪坡上，下一步就是与重力共舞。",
    date: "2024-02-20",
    src: "/images/life/fitness/a-skier-with-a-bag-on-a-snowy-slope-bY7uZyolzGk.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
  },


  // ==================== photography ====================
  {
    id: "p-01",
    category: "photography",
    title: "火箭升空",
    desc: "见证一束光撕裂夜空，那是人类最浪漫的倔强。",
    date: "2024-09-20",
    src: "/images/life/photography/rocket-launching-at-night-with-bright-flames-and-smoke--tT9l_dkakk.jpeg",
    orientation: "landscape",
    featured: true,
    layout: "wide",
  },
  {
    id: "p-02",
    category: "photography",
    title: "日落海浪",
    desc: "橙红色的天空倒映在海面上，浪潮一层一层涌来。",
    date: "2024-08-03",
    src: "/images/life/photography/ocean-waves-at-sunset-with-warm-orange-sky-eSLJG0y5S4U.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
  },
  {
    id: "p-03",
    category: "photography",
    title: "海岸礁石",
    desc: "浪花撞击礁石的瞬间，是大海最沉默的呐喊。",
    date: "2024-07-28",
    src: "/images/life/photography/rocky-coastline-with-waves-crashing-against-shore-AImfs6Xh1ZA.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "wide",
  },
  {
    id: "p-04",
    category: "photography",
    title: "落日飞鸟",
    desc: "海鸟掠过黄昏的天际线，像一封没有地址的信。",
    date: "2024-06-15",
    src: "/images/life/photography/a-bird-flies-across-a-hazy-sunset-over-the-ocean-t2vrK9yL2Bg.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
  },
  {
    id: "p-05",
    category: "photography",
    title: "叶上蝴蝶",
    desc: "翅膀上的纹路，是大自然写下的诗。",
    date: "2024-05-02",
    src: "/images/life/photography/a-butterfly-on-a-leaf-Kl3MvqEPJmY.jpeg",
    orientation: "portrait",
    featured: true,
    layout: "normal",
  },
  {
    id: "p-06",
    category: "photography",
    title: "蓝色漩涡",
    desc: "抽象的蓝白交织，像思绪在脑海中翻涌。",
    date: "2024-04-10",
    src: "/images/life/photography/abstract-blue-and-white-swirling-patterns-f9PtNFb9_iE.jpeg",
    orientation: "landscape",
    featured: false,
  },
  {
    id: "p-07",
    category: "photography",
    title: "郁金香田",
    desc: "整片黄色的花海，是春天最直白的告白。",
    date: "2024-03-25",
    src: "/images/life/photography/field-of-bright-yellow-tulips-in-bloom-Q_jNh-j8ybo.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "p-08",
    category: "photography",
    title: "键帽心事",
    desc: "四个按键，藏着创作者最常问自己的问题。",
    date: "2024-03-08",
    src: "/images/life/photography/four-keyboard-keys-with-words-and-symbols-48sADbm-Zvg.jpeg",
    orientation: "landscape",
    featured: false,
  },
  {
    id: "p-09",
    category: "photography",
    title: "满月当空",
    desc: "城市灯光再亮，也盖不住这一轮清辉。",
    date: "2024-02-24",
    src: "/images/life/photography/full-moon-glowing-in-the-dark-night-sky-mj_PJw9KZh4.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "p-10",
    category: "photography",
    title: "绿桥繁花",
    desc: "春日的桥与河，连空气都是粉色的。",
    date: "2024-02-14",
    src: "/images/life/photography/green-bridge-over-river-with-blooming-trees-in-foreground-BwQb8kPxl7w.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "p-11",
    category: "photography",
    title: "沙滩碎浪",
    desc: "潮水退去后，沙滩上留下交错的纹理。",
    date: "2024-01-20",
    src: "/images/life/photography/ocean-waves-crashing-on-a-sandy-beach-tu0sNnvcAYQ.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "p-12",
    category: "photography",
    title: "三角梅花",
    desc: "橙红色的花簇映着淡蓝的天空，热烈又安静。",
    date: "2023-12-12",
    src: "/images/life/photography/orange-bougainvillea-flowers-against-a-pale-sky-v8HyIkglUjA.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "p-13",
    category: "photography",
    title: "海岸植被",
    desc: "礁石、海浪与岸边的绿色植物，构成一幅自然的画卷。",
    date: "2023-11-28",
    src: "/images/life/photography/rocky-coastline-with-ocean-waves-and-coastal-plants-urV8KO0pJ9w.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "p-14",
    category: "photography",
    title: "海鸥与夕阳",
    desc: "它们飞向落日，像是去完成某个古老的约定。",
    date: "2023-10-15",
    src: "/images/life/photography/seagulls-fly-over-the-ocean-at-sunset-HcbMxftVAOo.jpeg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "p-15",
    category: "photography",
    title: "海平落日",
    desc: "太阳慢慢沉入海平面，世界进入温柔的静默。",
    date: "2023-09-30",
    src: "/images/life/photography/sun-setting-over-a-calm-ocean-horizon-jADSDvEZJpM.jpeg",
    orientation: "landscape",
    featured: false,
  },
  {
    id: "p-16",
    category: "photography",
    title: "黄昏立面",
    desc: "夕阳照亮建筑的一角，城市也有它的黄金时刻。",
    date: "2023-08-22",
    src: "/images/life/photography/sunlight-illuminates-a-building-facade-at-dusk-bjl4lrkxjzs.jpeg",
    orientation: "portrait",
    featured: false,
  },

  // ==================== travel ====================
  {
    id: "t-01",
    category: "travel",
    title: "香格里拉",
    desc: "",
    date: "2025-01-01",
    src: "/images/life/travel/xianggelila/xianggelila_01.jpg",
    orientation: "landscape",
    featured: true,
    images: [
      "/images/life/travel/xianggelila/xianggelila_01.jpg",
      "/images/life/travel/xianggelila/xianggelila_02.jpg",
      "/images/life/travel/xianggelila/xianggelila_03.jpg",
      "/images/life/travel/xianggelila/xianggelila_04.jpg",
      "/images/life/travel/xianggelila/xianggelila_05.jpg",
      "/images/life/travel/xianggelila/xianggelila_06.jpg",
      "/images/life/travel/xianggelila/xianggelila_07.jpg",
      "/images/life/travel/xianggelila/xianggelila_08.jpg",
      "/images/life/travel/xianggelila/xianggelila_09.jpg",
      "/images/life/travel/xianggelila/xianggelila_10.jpg",
      "/images/life/travel/xianggelila/xianggelila_11.jpg",
      "/images/life/travel/xianggelila/xianggelila_12.jpg"
    ],
  },
  {
    id: "t-02",
    category: "travel",
    title: "丽江",
    desc: "",
    date: "2024-12-01",
    src: "/images/life/travel/lijiang/lijiang_01.jpg",
    orientation: "landscape",
    featured: false,
    images: [
      "/images/life/travel/lijiang/lijiang_01.jpg",
      "/images/life/travel/lijiang/lijiang_02.jpg",
      "/images/life/travel/lijiang/lijiang_03.jpg",
      "/images/life/travel/lijiang/lijiang_04.jpg",
      "/images/life/travel/lijiang/lijiang_05.jpg"
    ],
  },
  {
    id: "t-03",
    category: "travel",
    title: "大理",
    desc: "",
    date: "2024-12-01",
    src: "/images/life/travel/dali/dali_01.jpg",
    orientation: "landscape",
    featured: false,
    images: [
      "/images/life/travel/dali/dali_01.jpg",
      "/images/life/travel/dali/dali_02.jpg",
      "/images/life/travel/dali/dali_03.jpg",
      "/images/life/travel/dali/dali_04.jpg",
      "/images/life/travel/dali/dali_05.jpg",
      "/images/life/travel/dali/dali_06.jpg",
      "/images/life/travel/dali/dali_07.jpg"
    ],
  },
  {
    id: "t-04",
    category: "travel",
    title: "昆明",
    desc: "",
    date: "2024-12-01",
    src: "/images/life/travel/kunming/kunming_01.jpg",
    orientation: "landscape",
    featured: false,
    images: [
      "/images/life/travel/kunming/kunming_01.jpg",
      "/images/life/travel/kunming/kunming_02.jpg",
      "/images/life/travel/kunming/kunming_03.jpg",
      "/images/life/travel/kunming/kunming_04.jpg",
      "/images/life/travel/kunming/kunming_05.jpg"
    ],
  },
  {
    id: "t-05",
    category: "travel",
    title: "上海",
    desc: "",
    date: "2024-11-01",
    src: "/images/life/travel/shanghai/shanghai_01.jpg",
    orientation: "landscape",
    featured: false,
    images: [
      "/images/life/travel/shanghai/shanghai_01.jpg",
      "/images/life/travel/shanghai/shanghai_02.jpg",
      "/images/life/travel/shanghai/shanghai_03.jpg",
      "/images/life/travel/shanghai/shanghai_04.jpg",
      "/images/life/travel/shanghai/shanghai_05.jpg"
    ],
  },
  {
    id: "t-06",
    category: "travel",
    title: "黄山",
    desc: "",
    date: "2024-05-01",
    src: "/images/life/travel/huangshan/huangshan_01.jpg",
    orientation: "landscape",
    featured: false,
    images: [
      "/images/life/travel/huangshan/huangshan_01.jpg",
      "/images/life/travel/huangshan/huangshan_02.jpg",
      "/images/life/travel/huangshan/huangshan_03.jpg",
      "/images/life/travel/huangshan/huangshan_04.jpg",
      "/images/life/travel/huangshan/huangshan_05.jpg",
      "/images/life/travel/huangshan/huangshan_06.jpg",
      "/images/life/travel/huangshan/huangshan_07.jpg",
      "/images/life/travel/huangshan/huangshan_08.jpg",
      "/images/life/travel/huangshan/huangshan_09.jpg"
    ],
  },
  {
    id: "t-07",
    category: "travel",
    title: "济南",
    desc: "",
    date: "2023-11-01",
    src: "/images/life/travel/jinan/jinan_01.jpg",
    orientation: "landscape",
    featured: false,
    images: [
      "/images/life/travel/jinan/jinan_01.jpg",
      "/images/life/travel/jinan/jinan_02.jpg",
      "/images/life/travel/jinan/jinan_03.jpg",
      "/images/life/travel/jinan/jinan_04.png",
      "/images/life/travel/jinan/jinan_05.jpg",
      "/images/life/travel/jinan/jinan_06.jpg",
      "/images/life/travel/jinan/jinan_07.jpg",
      "/images/life/travel/jinan/jinan_08.jpg",
      "/images/life/travel/jinan/jinan_09.jpg",
      "/images/life/travel/jinan/jinan_10.jpg"
    ],
  },
  {
    id: "t-08",
    category: "travel",
    title: "泰山",
    desc: "",
    date: "2023-11-02",
    src: "/images/life/travel/taishan/taishan_01.jpg",
    orientation: "landscape",
    featured: false,
    images: [
      "/images/life/travel/taishan/taishan_01.jpg",
      "/images/life/travel/taishan/taishan_02.jpg",
      "/images/life/travel/taishan/taishan_03.jpg",
      "/images/life/travel/taishan/taishan_04.jpg",
      "/images/life/travel/taishan/taishan_05.jpg",
      "/images/life/travel/taishan/taishan_06.jpg",
      "/images/life/travel/taishan/taishan_07.jpg",
      "/images/life/travel/taishan/taishan_08.jpg"
    ],
  },
  // ==================== moments ====================
  {
    id: "m-01",
    category: "moments",
    title: "上海东方明珠夜景",
    desc: "",
    date: "2025-02-03",
    src: "/images/life/moments/上海东方明珠夜景.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-02",
    category: "moments",
    title: "第一次做飞机",
    desc: "",
    date: "2025-02-02",
    src: "/images/life/moments/第一次做飞机.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-03",
    category: "moments",
    title: "学校大楼侧面",
    desc: "",
    date: "2025-02-01",
    src: "/images/life/moments/学校大楼侧面.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-04",
    category: "moments",
    title: "学校大楼夜景",
    desc: "",
    date: "2025-01-31",
    src: "/images/life/moments/学校大楼夜景.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-05",
    category: "moments",
    title: "学校篮球场傍晚",
    desc: "",
    date: "2025-01-30",
    src: "/images/life/moments/学校篮球场傍晚.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-06",
    category: "moments",
    title: "图书馆内景",
    desc: "",
    date: "2025-01-29",
    src: "/images/life/moments/图书馆内景.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-07",
    category: "moments",
    title: "我的桌面",
    desc: "",
    date: "2025-01-28",
    src: "/images/life/moments/我的桌面.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-08",
    category: "moments",
    title: "好吃的饭店",
    desc: "",
    date: "2025-01-27",
    src: "/images/life/moments/好吃的饭店.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-09",
    category: "moments",
    title: "牛肉塔可",
    desc: "",
    date: "2025-01-26",
    src: "/images/life/moments/牛肉塔可.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-10",
    category: "moments",
    title: "菌野菌子火锅",
    desc: "",
    date: "2025-01-25",
    src: "/images/life/moments/菌野菌子火锅.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-11",
    category: "moments",
    title: "济南老菜馆",
    desc: "",
    date: "2025-01-24",
    src: "/images/life/moments/济南老菜馆.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-12",
    category: "moments",
    title: "南京长江大桥桥墩",
    desc: "",
    date: "2025-01-23",
    src: "/images/life/moments/南京长江大桥桥墩.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-13",
    category: "moments",
    title: "玄武湖湖景",
    desc: "",
    date: "2025-01-22",
    src: "/images/life/moments/玄武湖湖景.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-14",
    category: "moments",
    title: "明孝陵隐秘小湖",
    desc: "",
    date: "2025-01-21",
    src: "/images/life/moments/明孝陵隐秘小湖.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-15",
    category: "moments",
    title: "紫金山俯瞰",
    desc: "",
    date: "2025-01-20",
    src: "/images/life/moments/紫金山俯瞰.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-16",
    category: "moments",
    title: "南京大屠杀遇难同胞纪念馆和平雕像",
    desc: "",
    date: "2025-01-19",
    src: "/images/life/moments/南京大屠杀遇难同胞纪念馆和平雕像.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-17",
    category: "moments",
    title: "景峰中心傍晚",
    desc: "",
    date: "2025-01-18",
    src: "/images/life/moments/景峰中心傍晚.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-18",
    category: "moments",
    title: "滨江公园傍晚天空",
    desc: "",
    date: "2025-01-17",
    src: "/images/life/moments/滨江公园傍晚天空.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-19",
    category: "moments",
    title: "古镇傍晚",
    desc: "",
    date: "2025-01-16",
    src: "/images/life/moments/古镇傍晚.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-20",
    category: "moments",
    title: "宏村清和月青旅",
    desc: "",
    date: "2025-01-15",
    src: "/images/life/moments/宏村清和月青旅.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-21",
    category: "moments",
    title: "黄山拍照",
    desc: "",
    date: "2025-01-14",
    src: "/images/life/moments/黄山拍照.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-22",
    category: "moments",
    title: "泰山景色",
    desc: "",
    date: "2025-01-13",
    src: "/images/life/moments/泰山景色.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-23",
    category: "moments",
    title: "珍珠泉龙头",
    desc: "",
    date: "2025-01-12",
    src: "/images/life/moments/珍珠泉龙头.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-24",
    category: "moments",
    title: "佛顶宫内景",
    desc: "",
    date: "2025-01-11",
    src: "/images/life/moments/佛顶宫内景.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-25",
    category: "moments",
    title: "云杉坪森林",
    desc: "",
    date: "2025-01-10",
    src: "/images/life/moments/云杉坪森林.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-26",
    category: "moments",
    title: "普达措小松鼠",
    desc: "",
    date: "2025-01-09",
    src: "/images/life/moments/普达措小松鼠.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-27",
    category: "moments",
    title: "香巴拉佛塔小石堆",
    desc: "",
    date: "2025-01-08",
    src: "/images/life/moments/香巴拉佛塔小石堆.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-28",
    category: "moments",
    title: "束河古镇",
    desc: "",
    date: "2025-01-07",
    src: "/images/life/moments/束河古镇.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-29",
    category: "moments",
    title: "风吹粉色的草",
    desc: "",
    date: "2025-01-06",
    src: "/images/life/moments/风吹粉色的草.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-30",
    category: "moments",
    title: "亚历山大鹦鹉",
    desc: "",
    date: "2025-01-05",
    src: "/images/life/moments/亚历山大鹦鹉.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-31",
    category: "moments",
    title: "玉龙雪山日照金山初始",
    desc: "",
    date: "2025-01-04",
    src: "/images/life/moments/玉龙雪山日照金山初始.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-32",
    category: "moments",
    title: "玉龙雪山日照金山完全",
    desc: "",
    date: "2025-01-03",
    src: "/images/life/moments/玉龙雪山日照金山完全.jpg",
    orientation: "portrait",
    featured: false,
  },
  {
    id: "m-33",
    category: "moments",
    title: "上山喝茶",
    desc: "",
    date: "2025-01-02",
    src: "/images/life/moments/上山喝茶.jpg",
    orientation: "portrait",
    featured: false,
  },
  // ==================== featured (homepage bestOfBest) ====================
  {
    id: "feat-01",
    category: "featured",
    title: "泰山",
    desc: "",
    date: "2023-11-02",
    src: "/images/life/featured/taishan.jpg",
    orientation: "portrait",
    featured: true,
    bestOfBest: true,
    layout: "normal",
  },
  {
    id: "feat-02",
    category: "featured",
    title: "黄山",
    desc: "",
    date: "2024-05-02",
    src: "/images/life/featured/huangshan.jpg",
    orientation: "landscape",
    featured: true,
    bestOfBest: true,
    layout: "wide",
  },
  {
    id: "feat-03",
    category: "featured",
    title: "云杉坪",
    desc: "",
    date: "2024-12-31",
    src: "/images/life/featured/yunshanping.jpg",
    orientation: "landscape",
    featured: true,
    bestOfBest: true,
    layout: "wide",
  },
  {
    id: "feat-zhuanjing",
    category: "featured",
    title: "转经筒",
    desc: "",
    date: "2023-11-04",
    src: "/images/life/featured/zhuanjingtong.jpg",
    orientation: "portrait",
    featured: true,
    bestOfBest: true,
    layout: "normal",
  },
  {
    id: "feat-06",
    category: "featured",
    title: "东方明珠",
    desc: "",
    date: "2024-10-13",
    src: "/images/life/featured/dongfangmingzhu.jpg",
    orientation: "landscape",
    featured: true,
    bestOfBest: true,
    layout: "normal",
  },
  {
    id: "feat-07",
    category: "featured",
    title: "松赞干布寺",
    desc: "",
    date: "2025-01-04",
    src: "/images/life/featured/songzanganbusi.jpg",
    orientation: "landscape",
    featured: true,
    bestOfBest: true,
    layout: "normal",
  },
  {
    id: "feat-08",
    category: "featured",
    title: "香巴拉佛塔",
    desc: "",
    date: "2025-01-03",
    src: "/images/life/featured/xiangbalafota.jpg",
    orientation: "landscape",
    featured: true,
    bestOfBest: true,
    layout: "normal",
  },
];

export function getFeaturedItems(category: string) {
  if (category === "all") {
    return lifeItems.filter((item) => item.bestOfBest);
  }
  return lifeItems.filter((item) => item.category === category && item.featured);
}

export function getTimelineItems(category: string) {
  if (category === "all") {
    return lifeItems
      .filter((item) => item.bestOfBest)
      .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  }
  return lifeItems
    .filter((item) => item.category === category)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export function getCategoryLabel(key: string) {
  return lifeCategories.find((c) => c.key === key)?.label ?? key;
}

export function getFitnessRecords() {
  return [...fitnessRecords].sort(
    (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
  );
}

export const arsenalImages: string[] = [
  "/images/life/arsenal/arsenal_1.jpg",
  "/images/life/arsenal/arsenal_2.jpg",
  "/images/life/arsenal/arsenal_3.jpg",
  "/images/life/arsenal/arsenal_4.jpg",
  "/images/life/arsenal/arsenal_5.jpg",
  "/images/life/arsenal/arsenal_6.jpg",
  "/images/life/arsenal/arsenal_7.jpg",
  "/images/life/arsenal/arsenal_8.jpg",
  "/images/life/arsenal/arsenal_9.jpg",
  "/images/life/arsenal/arsenal_10.jpg",
  "/images/life/arsenal/arsenal_11.jpg",
  "/images/life/arsenal/arsenal_12.jpg",
  "/images/life/arsenal/arsenal_13.jpg",
  "/images/life/arsenal/arsenal_14.jpg",
  "/images/life/arsenal/arsenal_15.jpg",
  "/images/life/arsenal/arsenal_16.jpg",
  "/images/life/arsenal/arsenal_17.jpg",
  "/images/life/arsenal/arsenal_18.jpg",
  "/images/life/arsenal/arsenal_19.jpg",
  "/images/life/arsenal/arsenal_20.jpg",
  "/images/life/arsenal/arsenal_21.jpg",
  "/images/life/arsenal/arsenal_22.jpg",
  "/images/life/arsenal/arsenal_23.jpg",
  "/images/life/arsenal/arsenal_24.jpg",
  "/images/life/arsenal/arsenal_25.jpg",
  "/images/life/arsenal/arsenal_26.jpg",
  "/images/life/arsenal/arsenal_27.jpg",
  "/images/life/arsenal/arsenal_28.jpg",
  "/images/life/arsenal/arsenal_29.jpg",
  "/images/life/arsenal/arsenal_30.jpg",
  "/images/life/arsenal/arsenal_31.jpg",
  "/images/life/arsenal/arsenal_32.jpg",
  "/images/life/arsenal/arsenal_33.jpg",
  "/images/life/arsenal/arsenal_34.jpg",
  "/images/life/arsenal/arsenal_35.jpg",
  "/images/life/arsenal/arsenal_36.jpg",
  "/images/life/arsenal/arsenal_37.jpg",
  "/images/life/arsenal/arsenal_38.jpg",
  "/images/life/arsenal/arsenal_39.jpg",
  "/images/life/arsenal/arsenal_40.jpg",
];
